
table dim_tempo

	column Date
		dataType: dateTime
		formatString: dd/MM/yyyy
		sourceColumn: Date
		summarizeBy: none

	column Ano
		dataType: int64
		formatString: 0
		sourceColumn: Ano
		summarizeBy: none

	column MesNum
		dataType: int64
		formatString: 0
		isHidden
		sourceColumn: MesNum
		summarizeBy: none

	column NomeMes
		dataType: string
		sourceColumn: NomeMes
		sortByColumn: MesNum
		summarizeBy: none

	column Trimestre
		dataType: string
		sourceColumn: Trimestre
		summarizeBy: none

	column DiaDaSemana
		dataType: string
		sourceColumn: DiaDaSemana
		summarizeBy: none

	partition dim_tempo = m
		mode: import
		source =
				let
					Inicio = #date(2026, 1, 1),
					Fim = #date(2026, 12, 31),
					Datas = List.Dates(Inicio, Duration.Days(Fim - Inicio) + 1, #duration(1, 0, 0, 0)),
					Tabela = Table.FromList(Datas, Splitter.SplitByNothing(), {"Date"}),
					TipoData = Table.TransformColumnTypes(Tabela, {{"Date", type date}}),
					Ano = Table.AddColumn(TipoData, "Ano", each Date.Year([Date]), Int64.Type),
					MesNum = Table.AddColumn(Ano, "MesNum", each Date.Month([Date]), Int64.Type),
					NomeMes = Table.AddColumn(MesNum, "NomeMes", each Date.MonthName([Date], "pt-BR"), type text),
					Trimestre = Table.AddColumn(NomeMes, "Trimestre", each "T" & Text.From(Date.QuarterOfYear([Date])), type text),
					DiaDaSemana = Table.AddColumn(Trimestre, "DiaDaSemana", each Date.DayOfWeekName([Date], "pt-BR"), type text)
				in
					DiaDaSemana
